//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public int ShowId { get; set; }
        public System.DateTime DateOfBooking { get; set; }
        public int NoOfSeats { get; set; }
        public string Email { get; set; }
        public int TotalAmount { get; set; }
        public int PaymentId { get; set; }
        public Nullable<System.DateTime> TimeOfBooking { get; set; }
    }
}
